# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_holdings_api import AccountHoldingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountHoldingsApi(unittest.TestCase):
    """AccountHoldingsApi unit test stubs"""

    def setUp(self):
        self.api = AccountHoldingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_filter_account_holdings(self):
        """Test case for filter_account_holdings

        Filter all Account Holdings records  # noqa: E501
        """
        pass

    def test_get_account_holding(self):
        """Test case for get_account_holding

        Retrieve a Account Holding record  # noqa: E501
        """
        pass

    def test_get_account_holdings(self):
        """Test case for get_account_holdings

        List all Account Holdings records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
