# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_security_balances_api import AccountSecurityBalancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountSecurityBalancesApi(unittest.TestCase):
    """AccountSecurityBalancesApi unit test stubs"""

    def setUp(self):
        self.api = AccountSecurityBalancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_filter_account_security_balances(self):
        """Test case for filter_account_security_balances

        Filter all Account Security Balances records  # noqa: E501
        """
        pass

    def test_get_account_security_balance(self):
        """Test case for get_account_security_balance

        Retrieve an Account Security Balance record  # noqa: E501
        """
        pass

    def test_get_account_security_balances(self):
        """Test case for get_account_security_balances

        List all Account Security Balances records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
