# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.heldaway_depository_transactions_api import HeldawayDepositoryTransactionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHeldawayDepositoryTransactionsApi(unittest.TestCase):
    """HeldawayDepositoryTransactionsApi unit test stubs"""

    def setUp(self):
        self.api = HeldawayDepositoryTransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_filter_heldaway_depository(self):
        """Test case for filter_heldaway_depository

        Filter all Heldaway Transactions  # noqa: E501
        """
        pass

    def test_get_heldaway_depositories(self):
        """Test case for get_heldaway_depositories

        List all Heldaway Transactions  # noqa: E501
        """
        pass

    def test_get_heldaway_depository(self):
        """Test case for get_heldaway_depository

        Retrieve a Heldaway Transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
