# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.client_user_profiles_api import ClientUserProfilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientUserProfilesApi(unittest.TestCase):
    """ClientUserProfilesApi unit test stubs"""

    def setUp(self):
        self.api = ClientUserProfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_client_user(self):
        """Test case for create_client_user

        Create a Client User Profile  # noqa: E501
        """
        pass

    def test_create_many_client_user_profiles(self):
        """Test case for create_many_client_user_profiles

        Create Client User Profiles  # noqa: E501
        """
        pass

    def test_detele_client_user(self):
        """Test case for detele_client_user

        Delete a Client User Profile  # noqa: E501
        """
        pass

    def test_detele_many_client_user_profiles(self):
        """Test case for detele_many_client_user_profiles

        Delete many Client User Profiles  # noqa: E501
        """
        pass

    def test_filter_client_user_profiles(self):
        """Test case for filter_client_user_profiles

        Filter all Client User Profiles  # noqa: E501
        """
        pass

    def test_get_client_user(self):
        """Test case for get_client_user

        Retrieve a Client User Profile  # noqa: E501
        """
        pass

    def test_get_client_user_profiles(self):
        """Test case for get_client_user_profiles

        List all Client User Profiles  # noqa: E501
        """
        pass

    def test_update_client_user(self):
        """Test case for update_client_user

        Update a Client User Profile  # noqa: E501
        """
        pass

    def test_update_client_user_profiles(self):
        """Test case for update_client_user_profiles

        Bulk Update Client User Profiles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
