# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.report_settings_api import ReportSettingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportSettingsApi(unittest.TestCase):
    """ReportSettingsApi unit test stubs"""

    def setUp(self):
        self.api = ReportSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_filter_report_settings(self):
        """Test case for filter_report_settings

        Filter all Report Settings  # noqa: E501
        """
        pass

    def test_get_report_setting(self):
        """Test case for get_report_setting

        Retrieve Report Settings  # noqa: E501
        """
        pass

    def test_get_report_settings(self):
        """Test case for get_report_settings

        List all Report Settings  # noqa: E501
        """
        pass

    def test_update_report_setting(self):
        """Test case for update_report_setting

        Update Report Settings  # noqa: E501
        """
        pass

    def test_update_report_settings(self):
        """Test case for update_report_settings

        Bulk Update Report Settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
