# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.usermanagement_clientprofiles_body import UsermanagementClientprofilesBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUsermanagementClientprofilesBody(unittest.TestCase):
    """UsermanagementClientprofilesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsermanagementClientprofilesBody(self):
        """Test UsermanagementClientprofilesBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.usermanagement_clientprofiles_body.UsermanagementClientprofilesBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
