# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.shared_file_api import SharedFileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSharedFileApi(unittest.TestCase):
    """SharedFileApi unit test stubs"""

    def setUp(self):
        self.api = SharedFileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_file(self):
        """Test case for create_file

        Create a Shared File  # noqa: E501
        """
        pass

    def test_detele_file(self):
        """Test case for detele_file

        Delete a Shared File  # noqa: E501
        """
        pass

    def test_filter_files(self):
        """Test case for filter_files

        Filter all Shared Files  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Retrieve a Shared File  # noqa: E501
        """
        pass

    def test_get_file_download_stream(self):
        """Test case for get_file_download_stream

        Retrieve a Shared File download stream  # noqa: E501
        """
        pass

    def test_get_files(self):
        """Test case for get_files

        List all Shared Files  # noqa: E501
        """
        pass

    def test_read_upload_files(self):
        """Test case for read_upload_files

        Upload Shared Files  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
