# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_balances_api import AccountBalancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountBalancesApi(unittest.TestCase):
    """AccountBalancesApi unit test stubs"""

    def setUp(self):
        self.api = AccountBalancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_balance(self):
        """Test case for get_account_balance

        Retrieve an Account Balance  # noqa: E501
        """
        pass

    def test_get_account_balances(self):
        """Test case for get_account_balances

        List all Account Balances  # noqa: E501
        """
        pass

    def test_get_account_current_balances(self):
        """Test case for get_account_current_balances

        List all Current Luca Account Balances  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
