# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.heldaway_accounts_api import HeldawayAccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHeldawayAccountsApi(unittest.TestCase):
    """HeldawayAccountsApi unit test stubs"""

    def setUp(self):
        self.api = HeldawayAccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_filter_heldaway_accounts(self):
        """Test case for filter_heldaway_accounts

        Filter all Heldaway Accounts  # noqa: E501
        """
        pass

    def test_get_heldaway_account(self):
        """Test case for get_heldaway_account

        Retrieve a Heldaway Account  # noqa: E501
        """
        pass

    def test_get_heldaway_accounts(self):
        """Test case for get_heldaway_accounts

        List all Heldaway Accounts  # noqa: E501
        """
        pass

    def test_update_heldaway_account(self):
        """Test case for update_heldaway_account

        Update a Heldaway Account  # noqa: E501
        """
        pass

    def test_update_heldaway_accounts(self):
        """Test case for update_heldaway_accounts

        Bulk Update Heldaway Accounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
