# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.fee_structures import FeeStructures  # noqa: E501
from swagger_client.rest import ApiException


class TestFeeStructures(unittest.TestCase):
    """FeeStructures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeeStructures(self):
        """Test FeeStructures"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fee_structures.FeeStructures()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
