# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20060_data import InlineResponse20060Data  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20060Data(unittest.TestCase):
    """InlineResponse20060Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20060Data(self):
        """Test InlineResponse20060Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20060_data.InlineResponse20060Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
