# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.jobs_api import JobsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_jobs(self):
        """Test case for clear_jobs

        Clear a Job  # noqa: E501
        """
        pass

    def test_filter_jobs(self):
        """Test case for filter_jobs

        Filter all Jobs  # noqa: E501
        """
        pass

    def test_get_job(self):
        """Test case for get_job

        Retrieve a Job  # noqa: E501
        """
        pass

    def test_get_jobs(self):
        """Test case for get_jobs

        List all Jobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
