# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fee_structure_api import FeeStructureApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFeeStructureApi(unittest.TestCase):
    """FeeStructureApi unit test stubs"""

    def setUp(self):
        self.api = FeeStructureApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_fee_structures(self):
        """Test case for create_fee_structures

        Create a Fee Structure  # noqa: E501
        """
        pass

    def test_create_many_fee_structures(self):
        """Test case for create_many_fee_structures

        Create Fee Structures  # noqa: E501
        """
        pass

    def test_detele_fee_structure(self):
        """Test case for detele_fee_structure

        Delete a Fee Structure  # noqa: E501
        """
        pass

    def test_detele_many_fee_structures(self):
        """Test case for detele_many_fee_structures

        Delete many Fee Structures  # noqa: E501
        """
        pass

    def test_filter_fee_structures(self):
        """Test case for filter_fee_structures

        Filter all Fee Structures  # noqa: E501
        """
        pass

    def test_get_fee_structure(self):
        """Test case for get_fee_structure

        Retrieve a Fee Structure  # noqa: E501
        """
        pass

    def test_get_fee_structures(self):
        """Test case for get_fee_structures

        List all Fee Structures  # noqa: E501
        """
        pass

    def test_update_fee_structure(self):
        """Test case for update_fee_structure

        Update a Fee Structure  # noqa: E501
        """
        pass

    def test_update_fee_structures(self):
        """Test case for update_fee_structures

        Bulk Update Fee Structures  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
