# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.authmanagement_apikeys_body import AuthmanagementApikeysBody  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthmanagementApikeysBody(unittest.TestCase):
    """AuthmanagementApikeysBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthmanagementApikeysBody(self):
        """Test AuthmanagementApikeysBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.authmanagement_apikeys_body.AuthmanagementApikeysBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
