# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.household_security_balances_api import HouseholdSecurityBalancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHouseholdSecurityBalancesApi(unittest.TestCase):
    """HouseholdSecurityBalancesApi unit test stubs"""

    def setUp(self):
        self.api = HouseholdSecurityBalancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_household_security_balances(self):
        """Test case for get_household_security_balances

        List mulitple Household Security Balances records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
