# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.usermanagement_roles_body import UsermanagementRolesBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUsermanagementRolesBody(unittest.TestCase):
    """UsermanagementRolesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsermanagementRolesBody(self):
        """Test UsermanagementRolesBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.usermanagement_roles_body.UsermanagementRolesBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
