# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InvestmentmanagementStrategiesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'firm_id': 'int',
        'security_allocations': 'InvestmentmanagementstrategiesSecurityAllocations'
    }

    attribute_map = {
        'name': 'name',
        'firm_id': 'firm_id',
        'security_allocations': 'security_allocations'
    }

    def __init__(self, name=None, firm_id=None, security_allocations=None):  # noqa: E501
        """InvestmentmanagementStrategiesBody - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._firm_id = None
        self._security_allocations = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if firm_id is not None:
            self.firm_id = firm_id
        if security_allocations is not None:
            self.security_allocations = security_allocations

    @property
    def name(self):
        """Gets the name of this InvestmentmanagementStrategiesBody.  # noqa: E501

        Name for the strategy  # noqa: E501

        :return: The name of this InvestmentmanagementStrategiesBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InvestmentmanagementStrategiesBody.

        Name for the strategy  # noqa: E501

        :param name: The name of this InvestmentmanagementStrategiesBody.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def firm_id(self):
        """Gets the firm_id of this InvestmentmanagementStrategiesBody.  # noqa: E501

        Id of the firm this strategy is associated with  # noqa: E501

        :return: The firm_id of this InvestmentmanagementStrategiesBody.  # noqa: E501
        :rtype: int
        """
        return self._firm_id

    @firm_id.setter
    def firm_id(self, firm_id):
        """Sets the firm_id of this InvestmentmanagementStrategiesBody.

        Id of the firm this strategy is associated with  # noqa: E501

        :param firm_id: The firm_id of this InvestmentmanagementStrategiesBody.  # noqa: E501
        :type: int
        """

        self._firm_id = firm_id

    @property
    def security_allocations(self):
        """Gets the security_allocations of this InvestmentmanagementStrategiesBody.  # noqa: E501


        :return: The security_allocations of this InvestmentmanagementStrategiesBody.  # noqa: E501
        :rtype: InvestmentmanagementstrategiesSecurityAllocations
        """
        return self._security_allocations

    @security_allocations.setter
    def security_allocations(self, security_allocations):
        """Sets the security_allocations of this InvestmentmanagementStrategiesBody.


        :param security_allocations: The security_allocations of this InvestmentmanagementStrategiesBody.  # noqa: E501
        :type: InvestmentmanagementstrategiesSecurityAllocations
        """

        self._security_allocations = security_allocations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvestmentmanagementStrategiesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvestmentmanagementStrategiesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
