# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Role(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'firm_id': 'int',
        'created_by_user_id': 'int',
        'name': 'str',
        'slug': 'str',
        'description': 'str',
        'permissions': 'list[str]',
        'created_at_utc': 'datetime',
        'updated_at_utc': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'firm_id': 'firm_id',
        'created_by_user_id': 'created_by_user_id',
        'name': 'name',
        'slug': 'slug',
        'description': 'description',
        'permissions': 'permissions',
        'created_at_utc': 'created_at_utc',
        'updated_at_utc': 'updated_at_utc'
    }

    def __init__(self, id=None, firm_id=None, created_by_user_id=None, name=None, slug=None, description=None, permissions=None, created_at_utc=None, updated_at_utc=None):  # noqa: E501
        """Role - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._firm_id = None
        self._created_by_user_id = None
        self._name = None
        self._slug = None
        self._description = None
        self._permissions = None
        self._created_at_utc = None
        self._updated_at_utc = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if firm_id is not None:
            self.firm_id = firm_id
        if created_by_user_id is not None:
            self.created_by_user_id = created_by_user_id
        if name is not None:
            self.name = name
        if slug is not None:
            self.slug = slug
        if description is not None:
            self.description = description
        if permissions is not None:
            self.permissions = permissions
        if created_at_utc is not None:
            self.created_at_utc = created_at_utc
        if updated_at_utc is not None:
            self.updated_at_utc = updated_at_utc

    @property
    def id(self):
        """Gets the id of this Role.  # noqa: E501

        Unique ID for this role object  # noqa: E501

        :return: The id of this Role.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Role.

        Unique ID for this role object  # noqa: E501

        :param id: The id of this Role.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def firm_id(self):
        """Gets the firm_id of this Role.  # noqa: E501

        ID of the owning firm  # noqa: E501

        :return: The firm_id of this Role.  # noqa: E501
        :rtype: int
        """
        return self._firm_id

    @firm_id.setter
    def firm_id(self, firm_id):
        """Sets the firm_id of this Role.

        ID of the owning firm  # noqa: E501

        :param firm_id: The firm_id of this Role.  # noqa: E501
        :type: int
        """

        self._firm_id = firm_id

    @property
    def created_by_user_id(self):
        """Gets the created_by_user_id of this Role.  # noqa: E501

        The user profile id of the creator user  # noqa: E501

        :return: The created_by_user_id of this Role.  # noqa: E501
        :rtype: int
        """
        return self._created_by_user_id

    @created_by_user_id.setter
    def created_by_user_id(self, created_by_user_id):
        """Sets the created_by_user_id of this Role.

        The user profile id of the creator user  # noqa: E501

        :param created_by_user_id: The created_by_user_id of this Role.  # noqa: E501
        :type: int
        """

        self._created_by_user_id = created_by_user_id

    @property
    def name(self):
        """Gets the name of this Role.  # noqa: E501

        Role name  # noqa: E501

        :return: The name of this Role.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Role.

        Role name  # noqa: E501

        :param name: The name of this Role.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def slug(self):
        """Gets the slug of this Role.  # noqa: E501

        Slugified role name  # noqa: E501

        :return: The slug of this Role.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this Role.

        Slugified role name  # noqa: E501

        :param slug: The slug of this Role.  # noqa: E501
        :type: str
        """

        self._slug = slug

    @property
    def description(self):
        """Gets the description of this Role.  # noqa: E501

        Description of this user role  # noqa: E501

        :return: The description of this Role.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Role.

        Description of this user role  # noqa: E501

        :param description: The description of this Role.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def permissions(self):
        """Gets the permissions of this Role.  # noqa: E501

        List of permission codes given by this role. See Permissions Overview.  # noqa: E501

        :return: The permissions of this Role.  # noqa: E501
        :rtype: list[str]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this Role.

        List of permission codes given by this role. See Permissions Overview.  # noqa: E501

        :param permissions: The permissions of this Role.  # noqa: E501
        :type: list[str]
        """

        self._permissions = permissions

    @property
    def created_at_utc(self):
        """Gets the created_at_utc of this Role.  # noqa: E501

        Timestamp for when the record was created  # noqa: E501

        :return: The created_at_utc of this Role.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at_utc

    @created_at_utc.setter
    def created_at_utc(self, created_at_utc):
        """Sets the created_at_utc of this Role.

        Timestamp for when the record was created  # noqa: E501

        :param created_at_utc: The created_at_utc of this Role.  # noqa: E501
        :type: datetime
        """

        self._created_at_utc = created_at_utc

    @property
    def updated_at_utc(self):
        """Gets the updated_at_utc of this Role.  # noqa: E501

        Timestamp for when the record was updated  # noqa: E501

        :return: The updated_at_utc of this Role.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at_utc

    @updated_at_utc.setter
    def updated_at_utc(self, updated_at_utc):
        """Sets the updated_at_utc of this Role.

        Timestamp for when the record was updated  # noqa: E501

        :param updated_at_utc: The updated_at_utc of this Role.  # noqa: E501
        :type: datetime
        """

        self._updated_at_utc = updated_at_utc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Role, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Role):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
