# coding: utf-8

"""
    Atlas API

    RESTful API for controlling and interacting with Atlas data  # noqa: E501

    OpenAPI spec version: 2.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UsermanagementClientprofilesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'firm_id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'household_id': 'int'
    }

    attribute_map = {
        'firm_id': 'firm_id',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'email': 'email',
        'household_id': 'household_id'
    }

    def __init__(self, firm_id=None, first_name=None, last_name=None, email=None, household_id=None):  # noqa: E501
        """UsermanagementClientprofilesBody - a model defined in Swagger"""  # noqa: E501
        self._firm_id = None
        self._first_name = None
        self._last_name = None
        self._email = None
        self._household_id = None
        self.discriminator = None
        if firm_id is not None:
            self.firm_id = firm_id
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if household_id is not None:
            self.household_id = household_id

    @property
    def firm_id(self):
        """Gets the firm_id of this UsermanagementClientprofilesBody.  # noqa: E501

        ID of the owning firm  # noqa: E501

        :return: The firm_id of this UsermanagementClientprofilesBody.  # noqa: E501
        :rtype: int
        """
        return self._firm_id

    @firm_id.setter
    def firm_id(self, firm_id):
        """Sets the firm_id of this UsermanagementClientprofilesBody.

        ID of the owning firm  # noqa: E501

        :param firm_id: The firm_id of this UsermanagementClientprofilesBody.  # noqa: E501
        :type: int
        """

        self._firm_id = firm_id

    @property
    def first_name(self):
        """Gets the first_name of this UsermanagementClientprofilesBody.  # noqa: E501

        User first name  # noqa: E501

        :return: The first_name of this UsermanagementClientprofilesBody.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UsermanagementClientprofilesBody.

        User first name  # noqa: E501

        :param first_name: The first_name of this UsermanagementClientprofilesBody.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UsermanagementClientprofilesBody.  # noqa: E501

        User last name  # noqa: E501

        :return: The last_name of this UsermanagementClientprofilesBody.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UsermanagementClientprofilesBody.

        User last name  # noqa: E501

        :param last_name: The last_name of this UsermanagementClientprofilesBody.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this UsermanagementClientprofilesBody.  # noqa: E501

        User email  # noqa: E501

        :return: The email of this UsermanagementClientprofilesBody.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UsermanagementClientprofilesBody.

        User email  # noqa: E501

        :param email: The email of this UsermanagementClientprofilesBody.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def household_id(self):
        """Gets the household_id of this UsermanagementClientprofilesBody.  # noqa: E501

        Alias for end_client_household_id  # noqa: E501

        :return: The household_id of this UsermanagementClientprofilesBody.  # noqa: E501
        :rtype: int
        """
        return self._household_id

    @household_id.setter
    def household_id(self, household_id):
        """Sets the household_id of this UsermanagementClientprofilesBody.

        Alias for end_client_household_id  # noqa: E501

        :param household_id: The household_id of this UsermanagementClientprofilesBody.  # noqa: E501
        :type: int
        """

        self._household_id = household_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsermanagementClientprofilesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsermanagementClientprofilesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
